FROM docker.io/library/ubuntu:18.04
RUN sudo su 
RUN apt update && apt upgrade
RUN mkdir /usr/local/tomcat/
ADD https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/bin/apache-tomcat-10.0.20.tar.gz /tmp/tomcat/apache-tomcat-10.0.20.tar.gz
RUN cd /tmp/tomcat && tar xvfz apache-tomcat-10.0.20.tar.gz
RUN cp -Rv apache-tomcat-10.0.20 /usr/local/tomcat
ADD **/*.war /usr/local/tomcat/webapps
EXPOSE 8080
CMD usr/local/tomcat/bin/catalina.sh run 
