
- hosts: all
  become: yes
  tasks:
   - name: start Docker
     service:
       name: docker
       state: started

   - name: start container
     service:
       name: abc-app
       image: Ngwaabanjong/apc-app:latest
       state: started
       ports:
        - 8000:8000
      
   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

